//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Uch_PracticeV3.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Text.RegularExpressions;

    public partial class Contract:IValidatableObject
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Contract()
        {
            this.Students = new HashSet<Student>();
        }
    
        [Display(Name = "Код")]
        [Required]
        public int Id { get; set; }

        [Display(Name = "Код организации")]
        [StringLength(8)]
        [Required]
        public string OrganizationId { get; set; }

        [Display(Name = "Дата заключения")]
        [Required]
        public System.DateTime Enter_Date { get; set; }

        [Display(Name = "Дата расторжения")]
        public Nullable<System.DateTime> Termination_Date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Student> Students { get; set; }
        public virtual Organization Organization { get; set; }

        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        {
            List<ValidationResult> errors = new List<ValidationResult>();

            if (new Regex(@"^\d{8}$").Matches(this.OrganizationId).Count <= 0)
            {
                errors.Add(new ValidationResult("Код ОКПО организации не соответствует шаблону"));
            }

            return errors;
        }
    }
}
