//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Uch_PracticeV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public string Id { get; set; }
        public string Surname { get; set; }
        public string Name { get; set; }
        public string Patronymic { get; set; }
        public int GroupId { get; set; }
        public int ContractId { get; set; }
        public int LeaderId { get; set; }
        public string FileNaming { get; set; }
        public string FileData { get; set; }
        public Nullable<int> Result { get; set; }
    
        public virtual Contract Contract { get; set; }
        public virtual Group Group { get; set; }
        public virtual Leader Leader { get; set; }
    }
}
